//let weight;
//console.log(typeof weight)

//let name = "Fulvia"
//let age = 35
//let stars = 1.76
//let isSubscribed = true 

//object

let student = {
    name: "Fulvia",
    age: 35,
    stars: 1.76,
    isSubscribed: true 
}

console.log(` ${studen.name} de idade ${student.age} pesa ${student.stars} kilos.`)

const John = {
    name : "John",
    age : 23,
    weight : 74.8,
    isSubscribed : true
}

students [1] = John
